### PR TITLE
fixed single " in condition

### PR DESCRIPTION
**Pull request by jaheba**
Having a non-valid string (missing 2nd quote) in a condition caused the program to stuck in a loop.

E.g::

``` javascript
simpleSqlParser.sql2ast('SELECT * FROM foo where "a')
```

### CODE REVIEW

**Comment by dsferruzza** [comment]
Thanks!
I'll fix some minor stuff and push a release on npm/bower!

**Comment by jaheba** [comment]
Cheers.

I further had some issues with case sensitive keywords like 'AS' or 'ON'. Don't know if this is intended or not.

**Comment by dsferruzza** [comment]
Feel free to open an issue if you want to discuss about that.
This project is a really naive implementation, so it is lighter than a real SQL parser, but also less reliable...

**Comment by jaheba** [comment]
What I really like is that the parser accepts parts, whilst others only accept full valid statements.
I'll open an issue for it.

**Pull request merged**
