### PR TITLE
Default behaviour of JOIN and ORDER BY

### PR DESCRIPTION
**Pull request by oshamin**

### CODE REVIEW

**Comment by oshamin** [comment]
Probably I forgot to use tab for indentation.

**Comment by dsferruzza** [comment]
Thanks!
This looks good to me, except for the indentation.

Could you fix it, please? (It's just a basic Find&Replace, but the diff would be more readable.)
You can also add yourself in the `contributors` array in `package.json`, if you wish to.

**Comment by oshamin** [comment]
Can I create fourth commit with changes or should recommit these three?

**Comment by dsferruzza** [comment]
I think you can just push new commits to your repo, and it will be automatically added to the pull request.

**Comment by oshamin** [comment]
I made it, please check

**Comment by dsferruzza** [comment]
Thanks a lot!
I will publish a new version to npm and bower soon.

If you want to say something or participate to the v2, please do: #6

**Pull request merged**
