### PR TITLE
Group by support

### PR DESCRIPTION
**Pull request by DVSoftware**

### CODE REVIEW

**Comment by dsferruzza** [comment]
Could you add some tests so I can see the behavior you expect?
Thanks by the way, I'll have a better look tonight!

**Comment by DVSoftware** [comment]
Hi, i added the tests

**Comment by dsferruzza** [comment]
It looks nice!
Thanks!

Could you remove the `.DS_Store` file you synced so I can merge?

**Comment by DVSoftware** [comment]
Removed, sorry about that

**Comment by dsferruzza** [comment]
Thanks for your contribution!
I'll deploy a new version on npm/bower right now!

**Pull request merged**
