### PR TITLE
Adds LIKE and IN operators support to readWord

### PR DESCRIPTION
**Pull request by joshuafcole**
Apologies for the whitespace edits, I'd normally do those as a separate commit if at all, but my editor at work is rather cleanup happy. :)

Cheers!

### CODE REVIEW

**Comment by dsferruzza** [comment]
It seems nice! Thanks!

Could you please make 2 changes before I merge?
- replace spaces indentation with tabs
- write tests for the features you added (see https://github.com/dsferruzza/simpleSqlParser#how-to-install-dev-tools to run tests)

**Comment by joshuafcole** [comment]
Ah, sorry about tabs vs. spaces. I'm using Light Table and it seems a little more opinionated than I am on the subject. I'll go ahead and do both shortly.

**Comment by dsferruzza** [comment]
Cool!

**Comment by joshuafcole** [comment]
Two basic unit tests added. I tried to maintain the style of the existing work. I can add a couple more if you like.

Of note, my implementation of IN leaves something to be desired -- it works fine, but I wish I'd been able to transform the right value of IN conditions into an array. Unfortunately, the tokenizer doesn't have any look-behind support to see that the previous operator was an IN, and while I could have gotten around that with some hackiness it didn't seem worthwhile. Would be good to do on V2 if you aren't already. I'm going to move forward using V1 at work for now, but as spare time permits I'll start playing with V2 and report back on any issues I run into.

Thanks again for your hard work!

**Comment by dsferruzza** [comment]
Thanks!
Your tests seems nice!
I'll release a new version soon.

I haven't started to work on the v2 condition parsing at all, so the behavior you mention is not implemented yet.
I hope I'll be able to do it soon :)

Thanks for you support!

**Comment by dsferruzza** [comment]
Can I add you to the contributor section of the `package.json` file?
Shall I take info from here https://github.com/joshuafcole?

**Comment by joshuafcole** [comment]
Sure! You're welcome to do so if you wish, though it was really a small contribution. I hope to be of more service in the future on V2. :)

**Pull request merged**
